/*
 * @Author: 丁攀峰 allen@leanktech.com
 * @Date: 2023-08-22 10:28:57
 * @LastEditors: 丁攀峰 allen@leanktech.com
 * @LastEditTime: 2023-08-31 14:47:59
 * @FilePath: /demo/functions/index.js
 */
export function onRequest(context, env) {
    const html = `<!DOCTYPE html>
    <body>
      <h1>Hello World</h1>
      <p>This markup was generated by a Cloudflare Worker.</p>
      <per>
        ${JSON.stringify(context,null,2)}
      </per>
      <per>
        ${JSON.stringify(env,null,2)}
      </per>
    </body>`

    return new Response(html, {
        headers: {
            'content-type': 'text/html;charset=UTF-8'
        }
    })
}
